stages:
  data_ingestion:
    cmd: python .\src\data\data_ingestion.py
    deps:
    - .\data\external\
    - .\src\data\data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - .\data\raw
  data_preprocessing:
    cmd: python .\src\data\data_preprocessing.py
    deps:
    - .\data\raw\
    - .\src\data\data_preprocessing.py
    outs:
    - .\data\interim\
  feature_engineering:
    cmd: python .\src\features\feature_engineering.py
    deps:
    - .\data\interim\
    - .\src\features\feature_engineering.py
    params:
    - feature_engineering
    outs:
    - .\data\processed\
  model_building:
    cmd: python .\src\model\model_building.py
    deps:
    - .\data\processed\
    - .\src\model\model_building.py
    params:
    - model_building
    outs:
    - models\lgbm_regressor.pkl
  model_evaluation:
    cmd: python .\src\model\model_evaluation.py
    deps:
    - .\data\processed\
    - .\models\lgbm_regressor.pkl
    - .\src\model\model_evaluation.py
    metrics:
    - reports/metrics.json
